Added new metrics for tracking latencies
yugabyte/tpcc pull request #110
Opened 2021-06-14 12:40 UTC by hbhanawat

Following is how we will report the metrics. It includes @robertsami's fix to not include the expected expectations as part of the calculation

```
================RESULTS================
             TPM-C |           31575.03
        Efficiency |             98.21%
Throughput (req/s) |            1169.67
07:13:09,024 (DBWorkload.java:643) INFO  - 
======================LATENCIES (INCLUDE RETRY ATTEMPTS)=====================
 Transaction |  Count   | Avg. Latency | P99 Latency | Connection Acq Latency
    NewOrder |   947251 |       101.67 |      544.49 |                  52.13
     Payment |   900957 |        66.38 |      259.18 |                  56.91
 OrderStatus |    85515 |        25.31 |      140.52 |                  36.66
    Delivery |    85612 |       357.16 |     1876.20 |                  35.51
  StockLevel |    86079 |       106.50 |      388.52 |                  34.05
        All  |  2105414 |        94.05 |      583.36 |                  52.13
07:13:09,028 (DBWorkload.java:667) INFO  - 
=====================================FAILURE LATENCIES====================================
 Transaction |  Count   | Percentage | Avg. Latency | P99 Latency | Connection Acq Latency
    NewOrder |     3037 |      0.32% |       149.12 |     1487.15 |                 369.12
     Payment |    13357 |      1.46% |        71.29 |      592.72 |                 560.42
 OrderStatus |        0 |      0.00% |        -1.00 |       -1.00 |                  -1.00
    Delivery |      153 |      0.18% |       371.22 |     2000.59 |                 211.01
  StockLevel |        0 |      0.00% |        -1.00 |       -1.00 |                  -1.00
        All  |    16547 |      0.78% |        88.35 |     1064.76 |                 522.08
07:13:12,442 (DBWorkload.java:594) INFO  - 
========================AGGREGATE LATENCIES========================
 Transaction |  Operation   |  Count   | Avg. Latency | P99 Latency
    NewOrder |   Fetch Work |   950288 |         3.87 |        0.00
    NewOrder |       Keying |   950288 |     18001.12 |    18000.07
    NewOrder |Op With Retry |   950288 |       154.97 |     2719.23
    NewOrder |     Thinking |   950288 |     11908.74 |    54871.06
     Payment |   Fetch Work |   914314 |         3.82 |        0.00
     Payment |       Keying |   914314 |      3001.17 |     3000.07
     Payment |Op With Retry |   914314 |       130.73 |     3568.15
     Payment |     Thinking |   914314 |     11915.81 |    54896.06
 OrderStatus |   Fetch Work |    85515 |         3.66 |        0.00
 OrderStatus |       Keying |    85515 |      2001.27 |     2000.07
 OrderStatus |Op With Retry |    85515 |        61.98 |     1264.70
 OrderStatus |     Thinking |    85515 |      9968.29 |    46077.06
    Delivery |   Fetch Work |    85765 |         3.71 |        0.00
    Delivery |       Keying |    85765 |      2001.08 |     2000.07
    Delivery |Op With Retry |    85765 |       393.01 |     2480.13
    Delivery |     Thinking |    85765 |      5006.44 |    22830.06
  StockLevel |   Fetch Work |    86079 |         3.85 |        0.00
  StockLevel |       Keying |    86079 |      2001.06 |     2000.07
  StockLevel |Op With Retry |    86079 |       140.56 |     1343.36
  StockLevel |     Thinking |    86079 |      4982.80 |    22755.03
        All  |   Fetch Work |  2121961 |         3.83 |        0.00
        All  |       Keying |  2121961 |      9597.38 |    18000.07
        All  |Op with Retry |  2121961 |       149.81 |     3095.97
        All  |     Thinking |  2121961 |     11273.65 |    53559.06
        All  |          All |  2121961 |     21024.67 |    66413.99

07:13:12,455 (DBWorkload.java:713) INFO  - 
========RETRIES (DEPRECATED STATS)===========
   Operation   | Total Created |    Conflicts  
      NewOrder |       1120501 |  4127 ( 0.37%)
       Payment |       1076148 | 18937 ( 1.76%)
   OrderStatus |        100323 |     0 ( 0.00%)
      Delivery |        100650 |   229 ( 0.23%)
    StockLevel |        100943 |     0 ( 0.00%)
```

2021-06-23 17:17 UTC, robertsami requested changes

2021-06-23 17:17 UTC, robertsami commented on src/com/oltpbenchmark/api/Worker.java
>                  ++totalTries[pieceOfWork.getType() - 1][attempt - 1];
why are we waiting to remove this?

2021-06-23 17:17 UTC, robertsami commented on src/com/oltpbenchmark/api/Worker.java
>              }
why are we waiting to remove this?

2021-06-23 17:17 UTC, robertsami commented on src/com/oltpbenchmark/api/Worker.java
> +            thinkTimeNs = System.nanoTime();
this naming isnt clear next to `think_time_msecs`

maybe prefer `endThinkTimeNs` or similar

2021-06-23 17:17 UTC, robertsami commented on src/com/oltpbenchmark/api/Worker.java
> +            executeTimeNs = System.nanoTime();
same comment re: clarity as below

2021-06-23 17:17 UTC, robertsami commented on src/com/oltpbenchmark/api/Worker.java
> +                    // before was either MEASURE and WARMUP and after was
"was either MEASURE or WARMUP"

or better yet, just say

"Only measure if the state after doWork completion was MEASURE." if that is the case, then it *must* be the case that the preState was MEASURE or WARMUP

2021-06-23 17:17 UTC, robertsami commented on src/com/oltpbenchmark/api/Worker.java
> +                    }
remove

2021-06-23 17:17 UTC, robertsami commented on src/com/oltpbenchmark/api/Worker.java
> +                    if ((preState == State.MEASURE || preState == State.WARMUP) &&
we dont need to check `(preState == State.MEASURE || preState == State.WARMUP)`. we _should_ check that the state after `doWork` is `MEASURE`

2021-06-23 17:17 UTC, robertsami commented on src/com/oltpbenchmark/TransactionLatencyRecord.java
> +/** Efficiently stores a record of (start time, latency) pairs. */
i think it stores more than this. can we update the comment?

2021-06-23 17:17 UTC, robertsami commented on src/com/oltpbenchmark/AggregateLatencyRecord.java
> +/** Efficiently stores a record of (start time, latency) pairs. */
update comment

2021-06-23 17:17 UTC, robertsami commented on src/com/oltpbenchmark/AggregateLatencyRecord.java
> +public class AggregateLatencyRecord extends LatencyRecord {
wonder if a better name for this is "PipelineLatencyRecord", since this is basically capturing latency of each step of the pipeline of a worker. I'm not sure what the word "Aggregate" is meant to signify

2021-06-23 17:17 UTC, robertsami commented on src/com/oltpbenchmark/TransactionLatencyRecord.java
> +    }
this code is essentially identical to the same method in AggregateLatencyRecord. maybe we can instead have a

```
protected LatencyRecord.Sample getNewSample() {
  return new ransactionLatencyRecord.Sample[ALLOC_SIZE];
}
```

and the common code can just exist in the base class?

2021-06-23 17:17 UTC, robertsami commented on src/com/oltpbenchmark/TransactionLatencyRecord.java
> +        ++nextIndex;
i think theres probably opportunity to share more of this code

2021-06-24 07:04 UTC, hbhanawat commented on src/com/oltpbenchmark/AggregateLatencyRecord.java
> +/** Efficiently stores a record of (start time, latency) pairs. */
Done.

2021-06-24 07:04 UTC, hbhanawat commented on src/com/oltpbenchmark/AggregateLatencyRecord.java
> +public class AggregateLatencyRecord extends LatencyRecord {
Made it workerTaskLatencyRecord

2021-06-24 07:04 UTC, hbhanawat commented on src/com/oltpbenchmark/TransactionLatencyRecord.java
> +/** Efficiently stores a record of (start time, latency) pairs. */
Done

2021-06-24 07:04 UTC, hbhanawat commented on src/com/oltpbenchmark/TransactionLatencyRecord.java
> +        ++nextIndex;
I tried that but given that the constructors have different parameters, it became difficult. Also the the impacted code would be less. Hence, leaving it as is for now

2021-06-24 07:04 UTC, hbhanawat commented on src/com/oltpbenchmark/TransactionLatencyRecord.java
> +    }
Done

2021-06-24 07:04 UTC, hbhanawat commented on src/com/oltpbenchmark/api/Worker.java
> +            executeTimeNs = System.nanoTime();
Done

2021-06-24 07:04 UTC, hbhanawat commented on src/com/oltpbenchmark/api/Worker.java
> +            thinkTimeNs = System.nanoTime();
Done

2021-06-24 07:04 UTC, hbhanawat commented on src/com/oltpbenchmark/api/Worker.java
> +                    // before was either MEASURE and WARMUP and after was
Done.

2021-06-24 07:04 UTC, hbhanawat commented on src/com/oltpbenchmark/api/Worker.java
> +                    }
Done.

2021-06-24 07:04 UTC, hbhanawat commented on src/com/oltpbenchmark/api/Worker.java
> +                    if ((preState == State.MEASURE || preState == State.WARMUP) &&
Well there are few other states and I don't understand the logic of those states in detail. Also, it is ok to be explicit here is what I thought.

2021-06-24 07:04 UTC, hbhanawat commented on src/com/oltpbenchmark/api/Worker.java
>                  ++totalTries[pieceOfWork.getType() - 1][attempt - 1];
Because number of transactions per retry is not included in the new stats. My next PR will take care of it.

2021-06-28 14:47 UTC, robertsami commented on src/com/oltpbenchmark/api/Worker.java
> +                    if ((preState == State.MEASURE || preState == State.WARMUP) &&
i think being explicit in this way is confusing to the reader of the code, but if paired with your comment which you've added i think its ok!

but please fix the condition here to actually check that the state after doWork was in fact measure

2021-06-29 12:04 UTC, hbhanawat commented on src/com/oltpbenchmark/api/Worker.java
> +                    if ((preState == State.MEASURE || preState == State.WARMUP) &&
You mean postState == MEASURE? That check is already the part of switch statement.

2021-06-29 12:16 UTC, hbhanawat commented on src/com/oltpbenchmark/api/Worker.java
> +                    if ((preState == State.MEASURE || preState == State.WARMUP) &&
Btw, this implementation is [Option 3: t1 falls within the measure phase]

I didn't change it as per Karthik's comment.

2021-06-29 14:23 UTC, robertsami approved these changes

2021-06-29 15:55 UTC, merged